### ISSUE TITLE
play music on lock screen

### ISSUE THREAD

**Issue by guivosgrau** [romankisil/eqMac2#11] opened 2017-07-27 08:33 UTC
When i put my mac to sleep and then i press the play/pause button to start a song, it is completely mute.

**Comment by romankisil** [comment] 2017-07-29 10:32
@guivosgrau can you elaborate? You can't play music when you mac "Sleeps" even without the app :)

**Comment by guivosgrau** [comment] 2017-07-29 21:45
For example, i like to listen music to sleep. I open spotify on my mac, set a song and put my mac to sleep. When the screen is off(black) I just press the play/pause button on the keyboard and music starts to play. With and without eqMac 1 it is possible to do this, but in the eqMac2 he just freeze and i need to restart it(eqmac2).

**Comment by romankisil** [comment] 2017-07-29 22:46
Still don't understand. It's impossible to play music when your Mac sleeps with or without eqMac. Unless my "sleep" you mean just turned off screen :/ When I put my Mac to sleep any music just stops playing, and pressing play just wake's my Mac up and send me to the Login screen

**Comment by guivosgrau** [comment] 2017-07-29 23:43
yeah man, that is what i mean...when i press the play button, the mac wake's and go to login screen. There is when the eqmac2 does not works, it just freeze

**Comment by romankisil** [comment] 2017-07-30 00:01
@guivosgrau then would you say this is the same issue as #6 and/or #12

**Comment by guivosgrau** [comment] 2017-07-30 01:03
I think it is too. Keep going, the app is amazing, I use about one year and i don't live without it. Hope that you solve all the issues with eqmac2. Thanks!

**Comment by romankisil** [comment] 2017-08-02 18:10
duplicate of #6 and #12

**Closed by romankisil** 2017-08-02 18:10 UTC

**Comment by nodeful** [comment] 2020-01-08 20:42
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment] 2020-04-04 16:40
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
