### ISSUE TITLE
Sleep Bug

### ISSUE THREAD

**Issue by gvanmourik** [romankisil/eqMac2#22] opened 2017-08-02 01:07 UTC
Sleep Bug macOS Sierra
------------------------------

OS: 
macOS Sierra 10.12.5

Media Player:
Spotify

Issue:
When eqMac2 is active upon putting the computer to sleep, eqMac2 is disabled and no sound is outputted when woken back up. When "Headphones", see photo, is clicked the sound, and eqMac2, resumes normal function.

<img width="201" alt="screen shot 2017-08-01 at 5 59 34 pm" src="https://user-images.githubusercontent.com/29561418/28853180-9a0e948e-76e3-11e7-80b5-f73e0001860b.png">

**Comment by romankisil** [comment] 2017-08-02 07:40
Duplicate of #12 and #6

**Closed by romankisil** 2017-08-02 07:40 UTC

**Comment by nodeful** [comment] 2020-01-08 20:42
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment] 2020-04-04 16:39
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
