### ISSUE TITLE
Focus not returned so difficult to exit full screen mode

### ISSUE THREAD

**Issue by skycafemix** [romankisil/eqMac2#93] opened 2017-11-21 11:05 UTC
Closing the Eq controls window does not return focus to the playing application. This makes it difficult to exit full screen mode (which is normally done by pressing Esc, Ctrl-Cmd-F, or the left-most Exit Full Screen button displayed on the touch bar) because the closed Eq application is still in the foreground even though it is hidden.
Touchbar MacBook Pro Late 2016 running Mac OS Sierra 10.12.6

**To reproduce:**
1. Play YouTube in Chrome full screen or play a video in QuickTime Player full screen
2. Click on Eq icon in menu bar
3. Close Eq by pressing Esc button (for me this button is on the touchbar)
4. Now try to escape full screen mode by clicking the Esc button.

**Expected behavior**
Focus is returned to the playing application (i.e. Chrome or QuickTime Player) and full screen mode is released, so the playing video becomes smaller. After step 3 above, the touchbar should show the Exit Full Screen button.

**Actual behavior**
- Focus is not returned to the playing application. So when you click Esc nothing happens (Full screen mode is not exitted). The user must figure out what is going on, then click once on the center of the screen to return focus to the playing application, and then press Esc or Ctrl-Cmd-F to exit full screen mode. 
- After step 3 the touchbar shows Esc button (for Eq app) instead of the Exit Full Screen button.
- This is especially confusing if you use Chrome to view the page in full screen mode (press ctrl-cmd-f) instead of viewing the video itself in full screen mode (by clicking the expand icon in the lower-right corner of the video frame), because both Chrome and Eq display Esc button in the touch bar the same way, so you cannot tell why it isn't working. When you play a YouTube video full screen however the touch bar changes to display an Exit Full Screen button so you can at least see that something is wrong.

**Comment by romankisil** [comment] 2017-11-21 19:59
Fixed in PR #95 will be released in Build 2.1
Will keep the issue open until then.

**Comment by romankisil** [comment] 2017-11-26 17:59
Build 2.1 has just been released. You can download it from https://bitgapp.com/eqmac
Could you please update and report if the issue is still relevant. Thanks :)

**Comment by romankisil** [comment] 2017-11-27 10:45
Tested on a couple systems, works as it should. Closing

**Closed by romankisil** 2017-11-27 10:45 UTC
Labels: bug, fixed

**Comment by nodeful** [comment] 2020-01-08 20:40
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment] 2020-04-04 16:38
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
