### ISSUE TITLE
Controls hidden in full screen mode

### ISSUE THREAD

**Issue by skycafemix** [romankisil/eqMac2#92] opened 2017-11-21 10:42 UTC
Seen when playing YouTube music video in Chrome or QuickTime Player.
Touchbar MacBook Pro Late 2016 running Mac OS Sierra 10.12.6

**To reproduce:**
1. Open a video file and set to view in full screen mode
2. Move mouse to top of screen so that the menu bar appears
3. Left-click or right-click on the Eq icon. (You do not have to click inside the Eq window.)
4. Move mouse to center of screen

**Expected behavior:** 
The menu bar disappears by animating off the top of the screen, but the Eq controls window should remain stationary and fully visible even when menu bar is hidden, so that you can change the volume while the video is playing.

**Actual behavior:**
The window menu bar disappears by animating off the top of the screen, and the Eq controls window is attached to it and does the same, partially moving off the top of the window. When the menu bar has fully disappeared, the Eq window is missing the top 1cm of height so the Volume control (or top of the Equalizer) is inaccessible.

Chrome YouTube - Volume missing (Version 62.0.3202.94 (Official Build) (64-bit))
<img width="1280" alt="chrome youtube - volume missing" src="https://user-images.githubusercontent.com/6860899/33068461-c2c35a90-cef4-11e7-9457-9e38c53d5b3c.png">

QuickTime Player - Eq missing
<img width="1280" alt="quicktime player - eq missing" src="https://user-images.githubusercontent.com/6860899/33068463-c45c0690-cef4-11e7-9d38-bf4c7c93f367.png">

**Comment by romankisil** [comment] 2017-11-21 20:00
This was fixed a long time ago. Will be live in Build 2.1

**Comment by romankisil** [comment] 2017-11-26 17:59
Build 2.1 has just been released. You can download it from https://bitgapp.com/eqmac
Could you please update and report if the issue is still relevant. Thanks :)

**Comment by romankisil** [comment] 2017-11-27 10:45
Tested on a couple systems, works as it should. Closing

**Closed by romankisil** 2017-11-27 10:45 UTC
Labels: fixed

**Comment by nodeful** [comment] 2020-01-08 20:40
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment] 2020-04-04 16:38
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
